export const MAX_REPORT_ISSUE_PHOTOS = 3;
export const REPORT_ISSUE_IMAGE_MAX_DIMENSION = 1600;
export const REPORT_ISSUE_IMAGE_QUALITY = 0.88;
export const REPORT_ISSUE_IMAGE_MAX_MB = 2.5;
export const REPORT_ISSUE_IMAGE_MAX_DATA_URL_LENGTH = 4_300_000;
