export const MAX_REPORT_ISSUE_PHOTOS = 3;
export const REPORT_ISSUE_IMAGE_MAX_DIMENSION = 2048;
export const REPORT_ISSUE_IMAGE_QUALITY = 0.92;
export const REPORT_ISSUE_IMAGE_MAX_MB = 3;
export const REPORT_ISSUE_IMAGE_MAX_DATA_URL_LENGTH = 4_300_000;
